map_type: costmap

obstacle_range: 2.0
raytrace_range: 2.5

transform_tolerance: 0.5

robot_radius: 0.45 
inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_my_robot/laser/scan, marking: true, clearing: true}
