map_type: costmap

obstacle_range: 3.0
raytrace_range: 3.5

transform_tolerance: 0.5

robot_radius: 0.5 
inflation_radius: 0.5

observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_my_robot/laser/scan, marking: true, clearing: true}
